### ISSUE TITLE
Volume too high on movie page

### ISSUE THREAD

**Issue by adripo** [LizardByte/Themerr-jellyfin#284]
### Describe the Bug

Theme starts at the maximum volume when opening a movie/series page without any option to set volume.

### Expected Behavior

Option to set volume in settings

**Comment by ReenigneArcher** [comment]
This plugin doesn't play the themes, the Jellyfin client does. This plugin only adds the themes. You'd have to request this option be added with the Jellyfin team.

**Comment by adripo** [comment]
Thank you, I will check with Jellyfin team.

**Comment by atlasveldine** [comment]
> Thank you, I will check with Jellyfin team.

@adripo Any word on this? This plugin works brilliantly, but the volume is so damned loud that it's unusable for me, lest I want my wife to wake up getting ear-r***d by anime OPs out of nowhere when she's sleeping and I decide to pop on some B-tier anime to fall asleep to...

As I really can't imagine that I'm the only other person with this issue, I'll offer a conceptual workaround for the more tech savvy: write a script/program which watches for new theme.mp3 files, then first normalizes the volume and then reduces the volume of the file. At least then, the worst issue you might have is themes being too quiet instead of absurdly loud.

**Comment by adripo** [comment]
@atlasveldine there is an open issue in jellyfin's repo
https://github.com/jellyfin/jellyfin-web/issues/3086
